<?xml version='1.0' encoding='ISO-8859-1' standalone='yes' ?>
<!DOCTYPE ontology [
<!ELEMENT ontology (entry_clusters) >
<!ATTLIST ontology language (aramaic|hebrew) #REQUIRED >
<!ELEMENT entry_clusters (entry_cluster*) >
<!ATTLIST entry_clusters >
<!ELEMENT ontology_entry (hebrew_lexeme,english_gloss) >
<!ATTLIST ontology_entry id CDATA #REQUIRED >
<!ELEMENT hebrew_lexeme (#PCDATA)* >
<!ATTLIST hebrew_lexeme >
<!ELEMENT entry_cluster (id_up_set,WordNet_synset,english_gloss,ontology_entries) >
<!ATTLIST entry_cluster id CDATA #REQUIRED >
<!ELEMENT id_up_set (id_up)* >
<!ATTLIST id_up_set >
<!ELEMENT id_up (#PCDATA)* >
<!ATTLIST id_up >
<!ELEMENT WordNet_synset (#PCDATA)* >
<!ATTLIST WordNet_synset >
<!ELEMENT english_gloss (#PCDATA)* >
<!ATTLIST english_gloss >
<!ELEMENT ontology_entries (ontology_entry)* >
<!ATTLIST ontology_entries >
]>

<ontology language="hebrew">
   <entry_clusters>
      <entry_cluster id="00d6bf1d0f5a8264b00e9f3b90e08b2a">
         <id_up_set>
            <id_up>8fcf26a9ee28198eee2775791995a6a1</id_up>
         </id_up_set>
         <WordNet_synset>{ body_part }-4467893</WordNet_synset>
         <english_gloss>body_part</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0102a5589c03f082e91b40a1a801b82c">
         <id_up_set>
            <id_up>229f805f3633cef1f0b4dc6b8e82e10a</id_up>
         </id_up_set>
         <WordNet_synset>{ time }-19843</WordNet_synset>
         <english_gloss>time</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0114f45dbb1d70cd7da434f394c646ef">
         <id_up_set>
            <id_up>b4e094767f01dbd0ca7fbb528ed3aaaf</id_up>
         </id_up_set>
         <WordNet_synset>{ figure, fig }-5852382</WordNet_synset>
         <english_gloss>figure</english_gloss>
         <ontology_entries>
            <ontology_entry id="9273314b4c7f436ad4c6f08555116a37">
               <hebrew_lexeme>T>NH/</hebrew_lexeme>
               <english_gloss>fig</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="01e99efa3a0266958a2252629982a029">
         <id_up_set>
            <id_up>fdf1f818c4b2c3511b81397f28f1a3ac</id_up>
         </id_up_set>
         <WordNet_synset>{ ask }-599108</WordNet_synset>
         <english_gloss>ask</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="02ad6d6c6fb5cb03ff085d88b97b1438">
         <id_up_set>
            <id_up>a36c55ed09698c17837d7183b219d583</id_up>
         </id_up_set>
         <WordNet_synset>{ sea }-7740659</WordNet_synset>
         <english_gloss>sea</english_gloss>
         <ontology_entries>
            <ontology_entry id="0df2eb5df0a8b7231c6a970f9494ef4f">
               <hebrew_lexeme>JM/</hebrew_lexeme>
               <english_gloss>sea</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="032db533cbba0190e4ef07255d30d355">
         <id_up_set>
            <id_up>c35552bb10f0470bda5fea4d3b90c533</id_up>
         </id_up_set>
         <WordNet_synset>{ fluid }-12630223</WordNet_synset>
         <english_gloss>fluid</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="03a1c61040d31548ea04e91995bb63d4">
         <id_up_set>
            <id_up>e67c957c06e52bd96789cfcc6cdb6ee9</id_up>
         </id_up_set>
         <WordNet_synset>{ boom, prosper, thrive, get_ahead, flourish, expand }-248526</WordNet_synset>
         <english_gloss>boom</english_gloss>
         <ontology_entries>
            <ontology_entry id="1d7eb1de58264660a583084a2f654b20">
               <hebrew_lexeme>FKL[</hebrew_lexeme>
               <english_gloss>prosper</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="03b54b11fa11ba7f5bd1c4a390cd2b67">
         <id_up_set>
            <id_up>7ef1574555ecef35835b89dd70fd12da</id_up>
         </id_up_set>
         <WordNet_synset>{ condition, status }-11745254</WordNet_synset>
         <english_gloss>condition</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="03f544af608aee27baf0f137e431a0da">
         <id_up_set>
            <id_up>8f9ea434f6a3ff0816a1f97153d078e9</id_up>
         </id_up_set>
         <WordNet_synset>{ plant_part }-11022946</WordNet_synset>
         <english_gloss>plant_part</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="045597ca044bba47683629953a641447">
         <id_up_set>
            <id_up>947c1440bbdfd3f85aef53575fd2b711</id_up>
         </id_up_set>
         <WordNet_synset>{ living_thing, animate_thing }-2956</WordNet_synset>
         <english_gloss>living_thing</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0490b7858fac07d0086a7281d324c2fd">
         <id_up_set>
            <id_up>fe3e8bca4a858b7566e31321a1fdb812</id_up>
         </id_up_set>
         <WordNet_synset>{ committee, commission }-6882991</WordNet_synset>
         <english_gloss>committee</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="06673d2906fafa538ee3a07be57a468b">
         <id_up_set>
            <id_up>323f2a02e9757efe6c5bbfc3927a2ddb</id_up>
         </id_up_set>
         <WordNet_synset>{ father, male_parent, begetter }-8272054</WordNet_synset>
         <english_gloss>father</english_gloss>
         <ontology_entries>
            <ontology_entry id="dc7033d484315a64ba31281bd5106233">
               <hebrew_lexeme>>B/</hebrew_lexeme>
               <english_gloss>father</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="067452446a78d006ca22c0d734569406">
         <id_up_set>
            <id_up>e14425ff0f5d2fa4668b0650fe14bf4d</id_up>
         </id_up_set>
         <WordNet_synset>{ surround, environ, encircle, circle, round, ring }-2133098</WordNet_synset>
         <english_gloss>surround</english_gloss>
         <ontology_entries>
            <ontology_entry id="34a4d8c1a293a84bb841658a3583e30e">
               <hebrew_lexeme>SBB[</hebrew_lexeme>
               <english_gloss>surround</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="069e2c2527750acf72b5cde96ec89665">
         <id_up_set>
            <id_up>2b273e08d360c6b237dcc7a6921dad79</id_up>
         </id_up_set>
         <WordNet_synset>{ clue, clew, cue }-5560449</WordNet_synset>
         <english_gloss>clue</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="06b32f49faccf8d3834b44e779c8954d">
         <id_up_set>
            <id_up>4111256c391f2acb85531c8431d58642</id_up>
         </id_up_set>
         <WordNet_synset>{ medium }-5272870</WordNet_synset>
         <english_gloss>medium</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="06c89fced8acd075eaa897656e633e0c">
         <id_up_set>
            <id_up>0f062011d569b1e81c4db5b7d55f8ab6</id_up>
         </id_up_set>
         <WordNet_synset>{ unit, social_unit }-6787448</WordNet_synset>
         <english_gloss>unit</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="07f0da836b2e462db28815ea070c1c1e">
         <id_up_set>
            <id_up>3d3b0d49ece06bb762c460e1a45f99c7</id_up>
         </id_up_set>
         <WordNet_synset>{ female, female_person }-7901005</WordNet_synset>
         <english_gloss>female</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="085a6d03bc32a1bb654938bee7622cf7">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ phenomenon }-25413</WordNet_synset>
         <english_gloss>phenomenon</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="08a15e1b155a7e89741cf4bba8a4560a">
         <id_up_set>
            <id_up>2263b029572fe0e4f345831c4a68111f</id_up>
         </id_up_set>
         <WordNet_synset>{ snake, serpent, ophidian }-1402291</WordNet_synset>
         <english_gloss>snake</english_gloss>
         <ontology_entries>
            <ontology_entry id="b4e61874fae90e9120eb9efed8621a4d">
               <hebrew_lexeme>NXC/</hebrew_lexeme>
               <english_gloss>serpent</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="08ca866f909b1baac0f5d6bd8c731242">
         <id_up_set>
            <id_up>5b634ae5f1d14df4e7800ac096726be7</id_up>
         </id_up_set>
         <WordNet_synset>{ linear_unit }-11473734</WordNet_synset>
         <english_gloss>linear_unit</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0ac208faeaa8827225e6dd1b461dabca">
         <id_up_set>
            <id_up>bf7572fecc65f14e8a8c03b040ccd3d8</id_up>
         </id_up_set>
         <WordNet_synset>{ biome }-6637260</WordNet_synset>
         <english_gloss>biome</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0ae8cc1c4bcce1e0513b810fee9ab389">
         <id_up_set>
            <id_up>b0d9c6471e2bd93604e2f8516383fcff</id_up>
         </id_up_set>
         <WordNet_synset>{ name, call }-811896</WordNet_synset>
         <english_gloss>name</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0ba4168e340eccb51a5e3eb28ee84cfb">
         <id_up_set>
            <id_up>a51de67516ff2d50a589a6a434dca6c1</id_up>
         </id_up_set>
         <WordNet_synset>{ report, describe, account }-762866</WordNet_synset>
         <english_gloss>report</english_gloss>
         <ontology_entries>
            <ontology_entry id="bde95028c6c2b0811ba073db34b4fe14">
               <hebrew_lexeme>NGD[</hebrew_lexeme>
               <english_gloss>make_known</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0c212d49d81d943dd8af7bf9ad288d13">
         <id_up_set>
            <id_up>14d148f001b20bb691f2b390839f7516</id_up>
         </id_up_set>
         <WordNet_synset>{ integer, whole_number }-11584525</WordNet_synset>
         <english_gloss>integer</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0c51bbba9834505f12e4d1c2e973f62c">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ act, human_action, human_activity }-22113</WordNet_synset>
         <english_gloss>act</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0c62f605aaf7159f3f8d0df994164335">
         <id_up_set>
            <id_up>dceab5206a522bce6f41399c7f9f6077</id_up>
         </id_up_set>
         <WordNet_synset>{ arouse, elicit, enkindle, kindle, evoke, fire, raise, provoke }-1382318</WordNet_synset>
         <english_gloss>arouse</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0c8869f13617ae820a1b31a8a4b20a76">
         <id_up_set>
            <id_up>d6e920d02a9b6bb00b78ab2d9e75f9f6</id_up>
         </id_up_set>
         <WordNet_synset>{ suffice, do, answer, serve }-2101102</WordNet_synset>
         <english_gloss>suffice</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0e50cdef0c90de011c214d22a288bab6">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ arrive, get, come }-1577035</WordNet_synset>
         <english_gloss>arrive</english_gloss>
         <ontology_entries>
            <ontology_entry id="7c3a46df02da4d529fff0982db40deee">
               <hebrew_lexeme>BW>[</hebrew_lexeme>
               <english_gloss>arrive</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0f062011d569b1e81c4db5b7d55f8ab6">
         <id_up_set>
            <id_up>6cd017c1ec2ea8b51023a195f7716c97</id_up>
         </id_up_set>
         <WordNet_synset>{ organization, organisation }-6683510</WordNet_synset>
         <english_gloss>organization</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0f2301250b1a7957147e7dd1958ce6e1">
         <id_up_set>
            <id_up>00d6bf1d0f5a8264b00e9f3b90e08b2a</id_up>
         </id_up_set>
         <WordNet_synset>{ organ }-4537584</WordNet_synset>
         <english_gloss>organ</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="0fab205fdd8983b882a8dbf9c0894347">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ work }-1896035</WordNet_synset>
         <english_gloss>work</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="10015e6600e2f717b126351b63ca119c">
         <id_up_set>
            <id_up>e64baea1204cd178e2c6a612a8e6a043</id_up>
         </id_up_set>
         <WordNet_synset>{ causal_agent, cause, causal_agency }-4911</WordNet_synset>
         <english_gloss>causal_agent</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="10dcf38f888f80fe0c1c50fa6895fd20">
         <id_up_set>
            <id_up>52d73ce52f443b318c45980beddea22b</id_up>
         </id_up_set>
         <WordNet_synset>{ administrative_district, administrative_division, territorial_division }-6992023</WordNet_synset>
         <english_gloss>administrative_district</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="10ed92b915ba5a6a6c24a9b2dab83f1f">
         <id_up_set>
            <id_up>575d70589afdc00f684dafb5a77f87dd</id_up>
         </id_up_set>
         <WordNet_synset>{ night, nighttime, dark }-12834176</WordNet_synset>
         <english_gloss>night</english_gloss>
         <ontology_entries>
            <ontology_entry id="ef605e8dc98eb4ecb270dbd46db3c521">
               <hebrew_lexeme>LJLH/</hebrew_lexeme>
               <english_gloss>night</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="10f020696eac2ba032e193b37200d5fd">
         <id_up_set>
            <id_up>4d5f870f5ec2bec04988a5fbafd5c5cb</id_up>
         </id_up_set>
         <WordNet_synset>{ wood }-12772693</WordNet_synset>
         <english_gloss>wood</english_gloss>
         <ontology_entries>
            <ontology_entry id="f2a51b3b20f2f975defd5ebc8acef6b6">
               <hebrew_lexeme>&lt;Y/</hebrew_lexeme>
               <english_gloss>piece_of_wood</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1174741fc939ef9ff7a213031332b14a">
         <id_up_set>
            <id_up>b0df9667762973fb3e22f0a963742c91</id_up>
         </id_up_set>
         <WordNet_synset>{ idea, thought }-4997818</WordNet_synset>
         <english_gloss>idea</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="119054791ec9373aaa3604fae8bd8b19">
         <id_up_set>
            <id_up>268635e516f18fa5087c4b512db45932</id_up>
         </id_up_set>
         <WordNet_synset>{ information }-4982819</WordNet_synset>
         <english_gloss>information</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="11c9b988499e1019e9380b1af2c86042">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ utter, emit, let_out, let_loose }-777192</WordNet_synset>
         <english_gloss>utter</english_gloss>
         <ontology_entries>
            <ontology_entry id="006c27eb0099f0216870c0b2159e9022">
               <hebrew_lexeme>CLX[</hebrew_lexeme>
               <english_gloss>let_loose</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="11cf11d8a610d690df0546e85b714e48">
         <id_up_set>
            <id_up>4f2e909f6d0e4ee3ee0a697da499db34</id_up>
         </id_up_set>
         <WordNet_synset>{ happening, occurrence, natural_event }-6067926</WordNet_synset>
         <english_gloss>happening</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="11e9cc672f798f9d6437ed08303d759c">
         <id_up_set>
            <id_up>f3e86cf89279a094469f6b78cb9bbb0e</id_up>
         </id_up_set>
         <WordNet_synset>{ work }-431993</WordNet_synset>
         <english_gloss>work</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="123b6243b87d5c33b0374ed5727b855b">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ desire, want }-1432869</WordNet_synset>
         <english_gloss>desire</english_gloss>
         <ontology_entries>
            <ontology_entry id="1ec109b467fb5202d77d9fb2f1d15a54">
               <hebrew_lexeme>XMD[</hebrew_lexeme>
               <english_gloss>desire</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1246cb52cd0584e15605be7763a7155e">
         <id_up_set>
            <id_up>9015515003fc32d3df82c8d2deee1567</id_up>
         </id_up_set>
         <WordNet_synset>{ spatial_property, spatiality }-4350089</WordNet_synset>
         <english_gloss>spatial_property</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1252c2b571659f0d905aca60493e61b2">
         <id_up_set>
            <id_up>e09762a3ce11147430251a320e9a1973</id_up>
         </id_up_set>
         <WordNet_synset>{ sensitivity, sensitiveness, sensibility }-4854014</WordNet_synset>
         <english_gloss>sensitivity</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="12f20dea8842794081a491c5299ab918">
         <id_up_set>
            <id_up>be83ef8a667092b7361256c81da47875</id_up>
         </id_up_set>
         <WordNet_synset>{ crowd, crowd_together }-1595540</WordNet_synset>
         <english_gloss>crowd</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="12fc5e79a871c7e88dea8270e669096b">
         <id_up_set>
            <id_up>7ef1574555ecef35835b89dd70fd12da</id_up>
         </id_up_set>
         <WordNet_synset>{ being, beingness, existence }-11771798</WordNet_synset>
         <english_gloss>being</english_gloss>
         <ontology_entries>
            <ontology_entry id="a58cb0ed92c38a8586c17b66100d444d">
               <hebrew_lexeme>&lt;YM/</hebrew_lexeme>
               <english_gloss>being</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="147aabce8f2083a11e9ff230a76bcf94">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ express, verbalize, verbalise, utter, give_tongue_to }-744133</WordNet_synset>
         <english_gloss>express</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="14d148f001b20bb691f2b390839f7516">
         <id_up_set>
            <id_up>15e146a29a5117be1ed4dfab69326072</id_up>
         </id_up_set>
         <WordNet_synset>{ number }-11455258</WordNet_synset>
         <english_gloss>number</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="14e6ef9400c75db0bd746f2a4729bff0">
         <id_up_set>
            <id_up>00d6bf1d0f5a8264b00e9f3b90e08b2a</id_up>
         </id_up_set>
         <WordNet_synset>{ abdomen, venter, stomach, belly }-4775636</WordNet_synset>
         <english_gloss>abdomen</english_gloss>
         <ontology_entries>
            <ontology_entry id="082cc365a3801e9eaab261a667cc697b">
               <hebrew_lexeme>GXWN/</hebrew_lexeme>
               <english_gloss>abdomen</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="14f1dc85d47943c499433614e624338e">
         <id_up_set>
            <id_up>397cf3f3e18ba274d7cac09e4322240e</id_up>
         </id_up_set>
         <WordNet_synset>{ shrub, bush }-11045834</WordNet_synset>
         <english_gloss>shrub</english_gloss>
         <ontology_entries>
            <ontology_entry id="77110e3db7d8eda8037ae4f7a484b1f5">
               <hebrew_lexeme>FJX/</hebrew_lexeme>
               <english_gloss>shrub</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="152f0fe512db4029163fa347c15ba13a">
         <id_up_set>
            <id_up>f8c558b28a0b10b754eb3877e4a8aa22</id_up>
         </id_up_set>
         <WordNet_synset>{ loop }-11708602</WordNet_synset>
         <english_gloss>loop</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1599eb3bad5502b6e418280332ab972d">
         <id_up_set>
            <id_up>1a434befae3f49ae09347ded52032f6f</id_up>
         </id_up_set>
         <WordNet_synset>{ control, command }-1919122</WordNet_synset>
         <english_gloss>control</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="15e146a29a5117be1ed4dfab69326072">
         <id_up_set>
            <id_up>c8429730ea3a1a3e978db365e44f88f3</id_up>
         </id_up_set>
         <WordNet_synset>{ definite_quantity }-11450469</WordNet_synset>
         <english_gloss>definite_quantity</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1601d28c6b8bb040b9c9d2b0e92379fb">
         <id_up_set>
            <id_up>9174e76295718ec192d542731cdfcc9a</id_up>
         </id_up_set>
         <WordNet_synset>{ Heaven }-7064858</WordNet_synset>
         <english_gloss>Heaven</english_gloss>
         <ontology_entries>
            <ontology_entry id="796ebdd215d1293f242ab1c131b63610">
               <hebrew_lexeme>CMJM/</hebrew_lexeme>
               <english_gloss>heaven</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1679e53943c55285a13cf51dcb7d8e44">
         <id_up_set>
            <id_up>e27efb8284fab0227bd3cd4c3acc495e</id_up>
         </id_up_set>
         <WordNet_synset>{ anger, choler, ire }-6248644</WordNet_synset>
         <english_gloss>anger</english_gloss>
         <ontology_entries>
            <ontology_entry id="dcc98533802325f2fadc52a500f0f5f2">
               <hebrew_lexeme>>P/</hebrew_lexeme>
               <english_gloss>anger</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="176a970b06a26901e8b4755429387de7">
         <id_up_set>
            <id_up>1a379e0f6c5a9cd3e0873f5a3f175996</id_up>
         </id_up_set>
         <WordNet_synset>{ carnelian, cornelian }-12507384</WordNet_synset>
         <english_gloss>carnelian</english_gloss>
         <ontology_entries>
            <ontology_entry id="9efd980de90c855e7c094b55575446f3">
               <hebrew_lexeme>CHM/</hebrew_lexeme>
               <english_gloss>carnelian</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1786f13b5a2ce08e93d4e30cce4b4530">
         <id_up_set>
            <id_up>b311ca7ae42496ceab52ecebc443723e</id_up>
         </id_up_set>
         <WordNet_synset>{ aculeus }-11024946</WordNet_synset>
         <english_gloss>aculeus</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="17b4832d6d6d0529a9659751d4e78583">
         <id_up_set>
            <id_up>3fbc08b0c9a57cf4cbc3fb61e9c7bbaa</id_up>
         </id_up_set>
         <WordNet_synset>{ fourth, 4th, quaternary }-2137489</WordNet_synset>
         <english_gloss>fourth</english_gloss>
         <ontology_entries>
            <ontology_entry id="edbd37c0087df04d4c7115fe46dd6e3a">
               <hebrew_lexeme>RBJ&lt;J/</hebrew_lexeme>
               <english_gloss>fourth</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="184361bd12919d9dd99f297e42095c9c">
         <id_up_set>
            <id_up>9e3af006f67109004f4869764792cdf8</id_up>
         </id_up_set>
         <WordNet_synset>{ sleep, slumber }-11826795</WordNet_synset>
         <english_gloss>sleep</english_gloss>
         <ontology_entries>
            <ontology_entry id="216ad31015f5ed8c2da40beea42c9ebe">
               <hebrew_lexeme>TRDMH/</hebrew_lexeme>
               <english_gloss>sleep</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="187a917ebfa56aec5ba4be0056ac897f">
         <id_up_set>
            <id_up>a64277473b03ae365b42356b03108726</id_up>
         </id_up_set>
         <WordNet_synset>{ crystal }-12578607</WordNet_synset>
         <english_gloss>crystal</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1964e60ef8844955a717c6de1e72058e">
         <id_up_set>
            <id_up>11cf11d8a610d690df0546e85b714e48</id_up>
         </id_up_set>
         <WordNet_synset>{ case, instance, example }-6088089</WordNet_synset>
         <english_gloss>case</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="19b06de1af58ff502de6179a2dc259cc">
         <id_up_set>
            <id_up>085a6d03bc32a1bb654938bee7622cf7</id_up>
         </id_up_set>
         <WordNet_synset>{ process }-11422319</WordNet_synset>
         <english_gloss>process</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="19b0aee0d52604a8e04125a371344eaf">
         <id_up_set>
            <id_up>58e158a4cfac58f0158d3edf1625b57f</id_up>
         </id_up_set>
         <WordNet_synset>{ proclaim }-773164</WordNet_synset>
         <english_gloss>proclaim</english_gloss>
         <ontology_entries>
            <ontology_entry id="70697304ceb7ef701cf333f9a6516a42">
               <hebrew_lexeme>QR>[</hebrew_lexeme>
               <english_gloss>proclaim</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="19ddef8b4dae72d6f219a8d64e22e341">
         <id_up_set>
            <id_up>b252cc9cd16c945b024fadd4636058d0</id_up>
            <id_up>f25c187f6236f860b6cb05ef926c937f</id_up>
         </id_up_set>
         <WordNet_synset>{ natural_resin }-12588682</WordNet_synset>
         <english_gloss>natural_resin</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1a25ac449e9e4320c9a3d5d49c701fa0">
         <id_up_set>
            <id_up>00d6bf1d0f5a8264b00e9f3b90e08b2a</id_up>
         </id_up_set>
         <WordNet_synset>{ process, outgrowth, appendage }-4696710</WordNet_synset>
         <english_gloss>process</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1a379e0f6c5a9cd3e0873f5a3f175996">
         <id_up_set>
            <id_up>3b8a041c7d12318a2f2a6faa0c35ce92</id_up>
            <id_up>56c71d415157ef44035ca01c8c9e3bbf</id_up>
         </id_up_set>
         <WordNet_synset>{ chalcedony, calcedony }-12511918</WordNet_synset>
         <english_gloss>chalcedony</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1a434befae3f49ae09347ded52032f6f">
         <id_up_set>
         </id_up_set>
         <WordNet_synset>Entity</WordNet_synset>
         <english_gloss>Entity</english_gloss>
         <ontology_entries>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1a80217b1773a6805bd8218a393b7635">
         <id_up_set>
            <id_up>d1341684d3b2d163bc43e9ad63c5e4e8</id_up>
         </id_up_set>
         <WordNet_synset>{ consider, take, deal, look_at }-584405</WordNet_synset>
         <english_gloss>consider</english_gloss>
         <ontology_entries>
            <ontology_entry id="1118e8076c27f2f906cc4e844c835fd4">
               <hebrew_lexeme>R>H[</hebrew_lexeme>
               <english_gloss>look_at</english_gloss>
            </ontology_entry>
         </ontology_entries>
      </entry_cluster>
      <entry_cluster id="1a9ccd440acf06c0a5d74bd341d5b86a">
         <id_up_set>